# Generated by Django 5.1.3 on 2024-11-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="USER",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("birth_date", models.CharField(blank=True, max_length=10, null=True)),
                ("hash", models.CharField(blank=True, max_length=255, null=True)),
                ("salt", models.CharField(blank=True, max_length=255, null=True)),
                ("role", models.IntegerField(null=True)),
                ("street_number", models.CharField(max_length=50)),
                ("street_name", models.CharField(max_length=250)),
                ("postal_code", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
    ]
