# Generated by Django 5.1.3 on 2024-11-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ALBUM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("artist", models.CharField(blank=True, max_length=100, null=True)),
                ("release_year", models.IntegerField()),
                ("tracks", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("images", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=10)),
                ("stock", models.IntegerField(null=True)),
            ],
        ),
    ]
